import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DevCards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <h1>DevCards</h1>
        <p>A development card collecting app.</p>
      </main>

      <footer className={styles.footer}>
        <p>Brought to you by Jeff Dazé</p>
      </footer>
    </div>
  )
}

export default Home
